### ISSUE TITLE
buttons and change temp

### ISSUE THREAD

**Issue by sparkescreative** [codmpm/esp-mqtt-btn-switch#5]
Hi

This isn't an issue at all - your example was the first I got working on my NodeMCU. 

I use the 2 relay gpio outputs differently.  1 powers a status LED and the other is for a relay.

I would like to expand it to have more buttons. and change the temp sensor from DHT to a DS18B20.

Could you help me at all.

**Comment by codmpm** [comment]
Hey,

not a bad idea - but there are by now many projects that should fit your needs.

See https://github.com/letscontrolit/ESPEasy for example :-)

**Comment by sparkescreative** [comment]
Ah ok. No fun though - looks like the ESPEasy has it all wrapped up. No need to learn anything! Thanks for your advice.

**Comment by codmpm** [comment]
Feel free to implement DS18B20 and add buttons as you like :-)
Happy to help and answer questions.
